<a href="https://colab.research.google.com/github/Vedant-Trivedi/Experiment-10/blob/main/EXP10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 10

##INTRODUCTION TO PANDAS
##used for Structured data EDA data cleaning

#Vedant Trivedi - 25070123121

In [ ]:
import pandas as pd
s= pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
#create DataFrame
data = {
    "Name":["A","B","C"],
    "Marks":[85,90,78]
}
df =pd.DataFrame(data)
print(df)

  Name  Marks
0    A     85
1    B     90
2    C     78

In [ ]:
#find the structure of the dataframe
df.shape

(3, 2)

In [ ]:
df.ndim

2

In [ ]:
df.size

6

In [ ]:
#display coloumn names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [ ]:
#check data types of each column
df.dtypes

Name     object
Marks     int64
dtype: object

In [ ]:
#access individual column
df["Name"]

0    A
1    B
2    C
Name: Name, dtype: object

In [ ]:
df["Marks"]

0    85
1    90
2    78
Name: Marks, dtype: int64

In [ ]:
#Access Name of first law
df.loc[0,"Name"]

'A'

In [ ]:
#create dataframe
date ={
    "Name":["A","B","C"],
    "MARKS":[85,90,78]
}
df = pd.DataFrame(date)
print(df)

  Name  MARKS
0    A     85
1    B     90
2    C     78

In [ ]:
#Add a new column
'''if marks 80-90-first class
if marks>=90-distinction
if marks>80-second class'''

df["grade"]=["first class","distinction","second class"]
print(df)

  Name  MARKS         grade
0    A     85   first class
1    B     90   distinction
2    C     78  second class

In [ ]:
#update data in dataframe
#change marks of student A to 88

df.loc[0,"Marks"]=88
df.iloc[1,1]=91

In [ ]:
#delete a column
#df.drop("grade",axis=1,inplace=true)
df1=df.drop("grade",axis=1)
print(df1)
print(df)

  Name  MARKS  Marks
0    A     85   88.0
1    B     91    NaN
2    C     78    NaN
  Name  MARKS         grade  Marks
0    A     85   first class   88.0
1    B     91   distinction    NaN
2    C     78  second class    NaN

In [ ]:
#perform basic statistical analysis
mean1=df["Marks"].mean()
mean1

np.float64(88.0)

In [ ]:
min1=df["MARKS"].min()
print(min1)

78

In [ ]:
max1=df["MARKS"].max()
print(max1)

91

In [ ]:
#Apply condition (filtering)
#display students scoring more than 80
df[df["MARKS"]>80]

  Name  MARKS        grade  Marks
0    A     85  first class   88.0
1    B     91  distinction    NaN